title: GitHub Lab Blog
author: Bart Golsteijn
email: nospam@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Test blog for lab assignment

# social links
twitter_username: your-twitter-handle
github_username:  bartgolsteijn

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
